version: '3.7'
services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4100:4100
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
